### PR TITLE
Lint fixes

### PR DESCRIPTION
**Pull request by hthetiot**
Fix Lint error when possible using npm run lint-fixes, add .editorconfig and .browserslistrc files

### CODE REVIEW

**Comment by hthetiot** [comment]
Build fail, therefor do not merge :)
- https://github.com/dilaouid/AlzheimApp/runs/4868813484?check_suite_focus=true
Screenshot 2022-01-19 at 15 14 16

**Comment by hthetiot** [comment]
Most of the changes in this PR are automatically made via 'npm run lint-fix'.
Remaining lint error need to be fixed manualy.

Ready for review @dilaouid :)

**Comment by hthetiot** [comment]
will resolve conflict for you

**Comment by hthetiot** [comment]
Done

**Comment by dilaouid** [comment]
Stunning ! Thanks a lot !

**Pull request merged**
